# Generated by Django 3.0.8 on 2020-07-12 06:50

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False
    
    dependencies = [
        ('blog', '0002_auto_20200711_1651'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Blog',
        ),
    ]
