name: Django CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install pipenv
      run: |
        pip install pipenv
    - name: Run Tests
      run: |
        pipenv install
        pipenv run python manage.py test
